#!/usr/bin/env ruby

require 'bundler'
require 'sinatra/base'

Bundler.require

module Projet
  def self.require_files *files
    files.each do |file|
      require File.expand_path(
        File.join(__FILE__, "..", file)
      )
    end
  end

  def self.run!
    Projet.require_files "command", "datas"

    Server.run!

    #arr = Datas.load

    #options = Command.get_options
    #arr = Datas.filtre_ville(arr, options[:ville])
    #arr = Datas.filtre_injury(arr, options[:injury])

    #nb_crash = arr.count

    #puts "Il y a eu #{nb_crash} accidents #{options[:ville] ? "à #{options[:ville]}" : ""}"
  end
end

Projet.require_files "server", "controllers/index_controller"
Projet.run!
